export const mockVideos = [
  {
    id: '6J3rsZPTTGQ',
    course: { id: 'course1', name: 'Korean 1', teacherId: 'abc123' },
    title: '님 vs 씨 – What’s the Difference?',
    thumbnail: 'https://i.ytimg.com/vi/6J3rsZPTTGQ/mqdefault.jpg',
  },
  {
    id: 'vDqOoI-4Z6M',
    course: { id: 1, name: 'Algebra 1', teacherId: 'teacher-1' },
    status: 'TEACHER_IN_PROGRESS',
    title:
      'What are variables, expressions, and equations? | Introduction to algebra | Algebra I | Khan Academy',
    thumbnail: 'https://i.ytimg.com/vi/vDqOoI-4Z6M/mqdefault.jpg',
  },
  {
    id: '-t6P3CjJhO4',
    course: { id: 1, name: 'Algebra 1', teacherId: 'teacher-1' },
    status: 'TEACHER_IN_PROGRESS',
    title: "Why you understand the math but CAN'T solve problems",
    thumbnail: 'https://i.ytimg.com/vi/-t6P3CjJhO4/mqdefault.jpg',
  },
  {
    id: 'h-nteIQ22R4',
    course: { id: 1, name: 'Algebra 2', teacherId: 'teacher-1' },
    status: 'TEACHER_IN_PROGRESS',
    title: 'power rule with negative exponents (KristaKingMath)',
    thumbnail: 'https://i.ytimg.com/vi/h-nteIQ22R4/mqdefault.jpg',
  },
  {
    id: 'oFMdkRPgt9s',
    course: { id: 1, name: 'Korean 1', teacherId: 'teacher-1' },
    status: 'TEACHER_IN_PROGRESS',
    title: '6 Essential Particles for Beginners | 동안, 마다, 쯤/정도, (이)나, 밖에 & 처럼',
    thumbnail: 'https://i.ytimg.com/vi/oFMdkRPgt9s/mqdefault.jpg',
  },
  {
    id: 'U08cAReeVW8',
    course: { id: 1, name: 'Korean 1', teacherId: 'teacher-1' },
    status: 'TEACHER_IN_PROGRESS',
    title: 'Korean Sentence Connectors With Billy Go | #8: As Soon As',
    thumbnail: 'https://i.ytimg.com/vi/U08cAReeVW8/mqdefault.jpg',
  },
  {
    id: '__Uw1SXPW7s',
    course: { id: 1, name: 'Calculus 1', teacherId: 'teacher-1' },
    status: 'TEACHER_IN_PROGRESS',
    title:
      'Introduction to integral calculus | Accumulation and Riemann sums | AP Calculus AB | Khan Academy',
    thumbnail: 'https://i.ytimg.com/vi/__Uw1SXPW7s/mqdefault.jpg',
  },
  {
    id: 'fIy5Wav4rok',
    course: { id: 1, name: 'Calculus 2', teacherId: 'teacher-1' },
    status: 'TEACHER_IN_PROGRESS',
    title: 'How to Do Implicit Differentiation (NancyPi)',
    thumbnail: 'https://i.ytimg.com/vi/fIy5Wav4rok/mqdefault.jpg',
  },
];

// export const mockVideos = [
//   {
//     id: '6J3rsZPTTGQ',
//     course: { id: 'course1', name: 'Korean 1', teacherId: 'abc123' },
//     title: '님 vs 씨 – What’s the Difference?',
//     thumbnail: 'https://i.ytimg.com/vi/6J3rsZPTTGQ/mqdefault.jpg',
//   },
//   {
//     id: '__Uw1SXPW7s',
//     course: { id: 'course1', name: 'Calculus 1', teacherId: 'abc123' },
//     status: 'TEACHER_IN_PROGRESS',
//     title:
//       'Introduction to integral calculus | Accumulation and Riemann sums | AP Calculus AB | Khan Academy',
//     thumbnail: 'https://i.ytimg.com/vi/__Uw1SXPW7s/mqdefault.jpg',
//   },
//   {
//     id: 'WsQQvHm4lSw',
//     course: { id: 1, name: 'Calculus 1', teacherId: 'teacher-1' },
//     status: 'TEACHER_IN_PROGRESS',
//     title: 'Understand Calculus in 35 Minutes',
//     thumbnail: 'https://i.ytimg.com/vi/WsQQvHm4lSw/mqdefault.jpg',
//   },
//   {
//     id: 'vDqOoI-4Z6M',
//     course: { id: 1, name: 'Algebra 1', teacherId: 'teacher-1' },
//     status: 'TEACHER_IN_PROGRESS',
//     title:
//       'What are variables, expressions, and equations? | Introduction to algebra | Algebra I | Khan Academy',
//     thumbnail: 'https://i.ytimg.com/vi/vDqOoI-4Z6M/mqdefault.jpg',
//   },
//   {
//     id: '-t6P3CjJhO4',
//     course: { id: 1, name: 'Algebra 1', teacherId: 'teacher-1' },
//     status: 'TEACHER_IN_PROGRESS',
//     title: "Why you understand the math but CAN'T solve problems",
//     thumbnail: 'https://i.ytimg.com/vi/-t6P3CjJhO4/mqdefault.jpg',
//   },
//   {
//     id: 'h-nteIQ22R4',
//     course: { id: 1, name: 'Algebra 2', teacherId: 'teacher-1' },
//     status: 'TEACHER_IN_PROGRESS',
//     title: 'power rule with negative exponents (KristaKingMath)',
//     thumbnail: 'https://i.ytimg.com/vi/h-nteIQ22R4/mqdefault.jpg',
//   },
//   {
//     id: 'oFMdkRPgt9s',
//     course: { id: 1, name: 'Korean 1', teacherId: 'teacher-1' },
//     status: 'TEACHER_IN_PROGRESS',
//     title: '6 Essential Particles for Beginners | 동안, 마다, 쯤/정도, (이)나, 밖에 & 처럼',
//     thumbnail: 'https://i.ytimg.com/vi/oFMdkRPgt9s/mqdefault.jpg',
//   },
//   {
//     id: 'U08cAReeVW8',
//     course: { id: 1, name: 'Korean 1', teacherId: 'teacher-1' },
//     status: 'TEACHER_IN_PROGRESS',
//     title: 'Korean Sentence Connectors With Billy Go | #8: As Soon As',
//     thumbnail: 'https://i.ytimg.com/vi/U08cAReeVW8/mqdefault.jpg',
//   },
// ];

// export const mockAnnotations = {};

export const mockAnnotations = [
  {
    id: 'W1768853086657',
    correctAnswer: '',
    headline: 'What pronoun is used most often in a casual setting',
    answerOptions: ['ssi', 'ah', 'nim', 'none of the above'],
    timestamp: 291,
    type: 'Multiple Choice',
    videoId: '6J3rsZPTTGQ',
  },
  {
    id: 'D1769108049125',
    correctAnswer: '',
    headline: 'Listening Checkpoint - What are we learning about in this video',
    answerOptions: [
      'How to find the hypotenuse',
      'At what x point does the curve change',
      'How to find the area beneath a curve',
      'What is the value of y',
    ],
    timestamp: 36,
    type: 'Multiple Choice',
    videoId: '__Uw1SXPW7s',
  },
  {
    id: 'Z1769108294910',
    correctAnswer: 'D',
    headline: 'How do we find the area under the curve?',
    answerOptions: [
      'Multiplying x and y',
      'Summing the section area',
      'Finding the width of x',
      'Finding the height of y',
    ],
    timestamp: 112,
    type: 'Multiple Choice',
    videoId: '__Uw1SXPW7s',
  },
  {
    id: 'S1769108456374',
    correctAnswer: 'A',
    headline: 'What is an integral?',
    answerOptions: [
      'The summing of infinite things',
      'The theory of relativity',
      'The integration of algebra and calculus',
      'The integrity of a slope',
    ],
    timestamp: 190,
    type: 'Multiple Choice',
    videoId: '__Uw1SXPW7s',
  },
  {
    id: 'N1769108570587',
    correctAnswer: 'A',
    headline: 'An integral is...',
    answerOptions: ['A sum', 'A function', 'A multiplication', 'A triangle'],
    timestamp: 277,
    type: 'Multiple Choice',
    videoId: '__Uw1SXPW7s',
  },
  {
    id: 'N1769113982361',
    correctAnswer: 'B',
    headline: 'In the past, what title was used more often?',
    answerOptions: ['할머니', '씨', '님', 'neither'],
    timestamp: 20,
    type: 'Multiple Choice',
    videoId: '6J3rsZPTTGQ',
  },
  {
    id: 'R1769178934303',
    correctAnswer: 'B',
    headline: 'In what situations is 님 most used?',
    answerOptions: ['Formal', 'Polite', 'Casual', 'Always'],
    timestamp: 72,
    type: 'Multiple Choice',
    videoId: '6J3rsZPTTGQ',
  },
  {
    id: 'C1769179214901',
    correctAnswer: 'C',
    headline: 'For whom do we NOT add the title 님?',
    answerOptions: ['Teachers', 'Seniors at work', 'Friends', 'Special status professionals'],
    timestamp: 111,
    type: 'Multiple Choice',
    videoId: '6J3rsZPTTGQ',
  },
  {
    id: 'X1769281402614',
    correctAnswer: '',
    headline: 'What is the purpose of this video?',
    answerOptions: [
      'To learn the difference between 님 and 씨',
      'To have fun',
      'For listening practice',
      'To demonstrate the app',
    ],
    timestamp: 4,
    type: 'Multiple Choice',
    videoId: '6J3rsZPTTGQ',
  },
  {
    id: 'G1769281553698',
    correctAnswer: '',
    headline: 'What happened to 님 and 씨 nowadays?',
    answerOptions: [
      'They are used interchangeably',
      'They have switched',
      'Nothing has changed',
      'Neither are used',
    ],
    timestamp: 16,
    type: 'Multiple Choice',
    videoId: '6J3rsZPTTGQ',
  },
  {
    id: 'U1769283125386',
    correctAnswer: '',
    headline: 'Adding a question early on for demonstration',
    answerOptions: [
      'This is answer a',
      'Adding in another answer b',
      'This is answer c',
      'Lastly answer d',
    ],
    timestamp: 4,
    type: 'Multiple Choice',
    videoId: 'vDqOoI-4Z6M',
  },
  {
    id: 'V1769283202401',
    correctAnswer: '',
    headline: 'This is a longer question to show the overflow text of a question header',
    answerOptions: [
      'This is the correct answer',
      'Answer B',
      'This is not an answer',
      'None of the above',
    ],
    timestamp: 64,
    type: 'Multiple Choice',
    videoId: 'vDqOoI-4Z6M',
  },
  {
    id: 'J1769283254276',
    correctAnswer: 'D',
    headline: 'What timestamp are we at in the video?',
    answerOptions: [
      '5 minutes 20 seconds',
      '3 minutes 26 seconds',
      '1 minute 30 seconds',
      '4 minutes 26 seconds',
    ],
    timestamp: 266,
    type: 'Multiple Choice',
    videoId: 'vDqOoI-4Z6M',
  },
];

//["{"id":"X1768587226895","dynamicContent":{"options":["first answer","second answer","third answer","fourth answer"]},"headline":"My headline / question","timestamp":"0:01:52","videoId":"__Uw1SXPW7s?si=Bf3uyaaM6V2QszuX"},{"id":"I1768587241031","dynamicContent":{"options":["again","again","agina","blah"]},"headline":"Anotha one","timestamp":"0:01:55","videoId":"__Uw1SXPW7s?si=Bf3uyaaM6V2QszuX"},{"id":"N1768588301975","dynamicContent":{"options":["asd","sd","dfsd","sd"]},"headline":"My headline / question","timestamp":"0:00:03","videoId":"__Uw1SXPW7s?si=Bf3uyaaM6V2QszuX"},{"id":"W1768853086657","correctAnswer":"","headline":"What pronoun is used most often in a casual setting","answerOptions":["ssi","ah","nim","none of the above"],"timestamp":291,"type":"Multiple Choice","videoId":"6J3rsZPTTGQ"},{"id":"D1769108049125","correctAnswer":"","headline":"Listening Checkpoint - What are we learning about in this video","answerOptions":["How to find the hypotenuse","At what x point does the curve change","How to find the area beneath a curve","What is the value of y"],"timestamp":36,"type":"Multiple Choice","videoId":"__Uw1SXPW7s"},{"id":"Z1769108294910","correctAnswer":"D","headline":"How do we find the area under the curve?","answerOptions":["Multiplying x and y","Summing the section area","Finding the width of x","Finding the height of y"],"timestamp":112,"type":"Multiple Choice","videoId":"__Uw1SXPW7s"},{"id":"S1769108456374","correctAnswer":"A","headline":"What is an integral?","answerOptions":["The summing of infinite things","The theory of relativity","The integration of algebra and calculus","The integrity of a slope"],"timestamp":190,"type":"Multiple Choice","videoId":"__Uw1SXPW7s"},{"id":"N1769108570587","correctAnswer":"A","headline":"An integral is...","answerOptions":["A sum","A function","A multiplication","A triangle"],"timestamp":277,"type":"Multiple Choice","videoId":"__Uw1SXPW7s"},{"id":"N1769113982361","correctAnswer":"B","headline":"In the past, what title was used more often?","answerOptions":["할머니","씨","님","neither"],"timestamp":20,"type":"Multiple Choice","videoId":"6J3rsZPTTGQ"},{"id":"R1769178934303","correctAnswer":"B","headline":"In what situations is 님 most used?","answerOptions":["Formal","Polite","Casual","Always"],"timestamp":72,"type":"Multiple Choice","videoId":"6J3rsZPTTGQ"},{"id":"C1769179214901","correctAnswer":"C","headline":"For whom do we NOT add the title 님?","answerOptions":["Teachers","Seniors at work","Friends","Special status professionals"],"timestamp":111,"type":"Multiple Choice","videoId":"6J3rsZPTTGQ"},{"id":"X1769281402614","correctAnswer":"","headline":"What is the purpose of this video?","answerOptions":["To learn the difference between 님 and 씨","To have fun","For listening practice","To demonstrate the app"],"timestamp":4,"type":"Multiple Choice","videoId":"6J3rsZPTTGQ"},{"id":"G1769281553698","correctAnswer":"","headline":"What happened to 님 and 씨 nowadays?","answerOptions":["They are used interchangeably","They have switched","Nothing has changed","Neither are used"],"timestamp":16,"type":"Multiple Choice","videoId":"6J3rsZPTTGQ"},{"id":"U1769283125386","correctAnswer":"","headline":"Adding a question early on for demonstration","answerOptions":["This is answer a","Adding in another answer b","This is answer c","Lastly answer d"],"timestamp":4,"type":"Multiple Choice","videoId":"vDqOoI-4Z6M"},{"id":"V1769283202401","correctAnswer":"","headline":"This is a longer question to show the overflow text of a question header","answerOptions":["This is the correct answer","Answer B","This is not an answer","None of the above"],"timestamp":64,"type":"Multiple Choice","videoId":"vDqOoI-4Z6M"},{"id":"J1769283254276","correctAnswer":"D","headline":"What timestamp are we at in the video?","answerOptions":["5 minutes 20 seconds","3 minutes 26 seconds","1 minute 30 seconds","4 minutes 26 seconds"],"timestamp":266,"type":"Multiple Choic
